* Evil Better Visual Line
[[http://melpa.org/#/evil-better-visual-line][file:http://melpa.org/packages/evil-better-visual-line-badge.svg]]

Back in my vim days, I much preferred to default to moving on visual lines as opposed to source lines,
perhaps best expressed with the following lines from my ~.vimrc~:
#+BEGIN_SRC .vimrc
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
#+END_SRC
However, this rebinding is somewhat annoying in visual line and visual block mode, as moving on visual lines
is almost never the intent in those modes. This package provides two commands, ~evil-better-visual-line-next-line~ and
~evil-better-visual-line-previous-line~, which act like ~gj~ and ~gk~ unless in either of those modes
(or states in evil terminology), in which case they act like ~j~ and ~k~. ~evil-better-visual-line-on~ is also
provided as a convenient way of binding these two commands to ~j~ and ~k~.

** Installation

*** Melpa:
Install from MELPA directly with ~M-x package-install evil-better-visual-line~.
See the [[https://github.com/milkypostman/melpa][melpa repository]] for details about how to set up MELPA if you have not already done so.

**** use-package
I would recommend jwiegley's excellent [[https://github.com/jwiegley/use-package][use-package]] to install if you can:

#+BEGIN_SRC emacs-lisp
(use-package evil-better-visual-line
  :ensure t
  :config
  (evil-better-visual-line-on))
#+END_SRC

**** [[http://spacemacs.org/][spacemacs]]
I have a [[spacemacs][layer in my .spacemacs.d]] set up to load this package and call ~evil-better-visual-line-on~,
which you can add to your own private layer directory if you would like to use this package with spacemacs.

*** Manually:
Download with:
#+begin_src bash
git clone git@github.com:YourFin/evil-better-visual-line.git
#+end_src

Make sure that the resulting folder is in your load path.
Example in ~.emacs.d/init.el~ for .emacs.d/evil-better-visual-line:
#+begin_src emacs-lisp
(add-to-list 'load-path (expand-file-name "/evil-better-visual-mave"))
#+end_src

Random folder on your system:
#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/evil-better-visual-mave")
#+end_src

And then turn it on:
#+begin_src emacs-lisp
(require 'evil-better-visual-line)
(evil-better-visual-line-on)
#+end_src
